// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://slctpztvljcvdtabxvkl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNsY3RwenR2bGpjdmR0YWJ4dmtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxODA2MjcsImV4cCI6MjA2NTc1NjYyN30.X5BZ-QuGMw5UXvGdnBQ5JR5SdPhlzPecW_HcIwm9kXE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);